In [1]:
from sklearn.datasets import load_diabetes

import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
from sklearn.model_selection import train_test_split
X,y = load_diabetes(return_X_y=True)
print(X.shape)
print(y.shape)
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=2)
reg = LinearRegression()
reg.fit(X_train,y_train)
print(reg.coef_)
print(reg.intercept_)
y_pred = reg.predict(X_test)
r2_score(y_test,y_pred)

(442, 10)
(442,)
[  -9.15865318 -205.45432163  516.69374454  340.61999905 -895.5520019
  561.22067904  153.89310954  126.73139688  861.12700152   52.42112238]
151.88331005254167


0.4399338661568968

In [2]:
# custom mini batch gradient descent

In [8]:
import random
class MBGDRegressor:

    def __init__(self,batch_size,learning_rate=0.1,epochs=100):
        self.coef_=None
        self.interccept=None
        self.lr=learning_rate
        self.epochs=epochs
        self.batch_size=batch_size


    def fit(self,X_train,y_train):
        # init your coefs
        self.interccept=0
        self.coef_=np.ones(X_train.shape[1])

        for i in range(self.epochs):
            
            for j in range(int(X_train.shape[0]/self.batch_size)):
                
                idx = random.sample(range(X_train.shape[0]),self.batch_size)
                
                y_hat = np.dot(X_train[idx],self.coef_) + self.intercept_
                #print("Shape of y_hat",y_hat.shape)
                intercept_der = -2 * np.mean(y_train[idx] - y_hat)
                self.intercept_ = self.intercept_ - (self.lr * intercept_der)

                coef_der = -2 * np.dot((y_train[idx] - y_hat),X_train[idx])
                self.coef_ = self.coef_ - (self.lr * coef_der)
        
        print(self.intercept_,self.coef_)
    
    def predict(self,X_test):
        return np.dot(X_test,self.coef_) + self.intercept_



In [9]:
mbr = MBGDRegressor(batch_size=int(X_train.shape[0]/50),learning_rate=0.01,epochs=100)

In [10]:
mbr.fit(X_train,y_train)

AttributeError: 'MBGDRegressor' object has no attribute 'intercept_'

In [11]:

y_pred = mbr.predict(X_test)

AttributeError: 'MBGDRegressor' object has no attribute 'intercept_'

In [14]:
r2_score(y_test,y_pred)

0.4399338661568968

In [13]:
from sklearn.linear_model import SGDRegressor
sgd = SGDRegressor(learning_rate='constant',eta0=0.1)
batch_size = 35

for i in range(100):
    
    idx = random.sample(range(X_train.shape[0]),batch_size)
    sgd.partial_fit(X_train[idx],y_train[idx])

In [15]:
sgd.coef_

array([  30.08888419,  -78.64196504,  360.51142029,  237.28213356,
          5.46934691,  -29.04575859, -197.54945835,  139.22885021,
        322.08305589,  115.98760165])

In [16]:
sgd.intercept_

array([169.21969756])

In [17]:
sgd.intercept_

array([169.21969756])

In [18]:
y_pred = sgd.predict(X_test)

In [19]:
r2_score(y_test,y_pred)

0.38903077235756844